In [1]:
import numpy as np
import pandas as pd

In [2]:
student_df = pd.read_csv('../../datasets/student_mat_processed01.csv')

In [5]:
student_df.head(10)

,sex,age,address,famsize,Medu,Fedu,traveltime,studytime,failures,schoolsup,...,Fjob_other,Fjob_services,Fjob_teacher,reason_course,reason_home,reason_other,reason_reputation,guardian_father,guardian_mother,guardian_other
0,0,18,1,0,4,4,2,2,0,1,...,0,0,1,1,0,0,0,0,1,0
1,0,17,1,0,1,1,1,2,0,0,...,1,0,0,1,0,0,0,1,0,0
2,0,15,1,1,1,1,1,2,3,1,...,1,0,0,0,0,1,0,0,1,0
3,0,15,1,0,4,2,1,3,0,0,...,0,1,0,0,1,0,0,0,1,0
4,0,16,1,0,3,3,1,2,0,0,...,1,0,0,0,1,0,0,1,0,0
5,1,16,1,1,4,3,1,2,0,0,...,1,0,0,0,0,0,1,0,1,0
6,1,16,1,1,2,2,1,2,0,0,...,1,0,0,0,1,0,0,0,1,0
7,0,17,1,0,4,4,2,2,0,1,...,0,0,1,0,1,0,0,0,1,0
8,1,15,1,1,3,2,1,2,0,0,...,1,0,0,0,1,0,0,0,1,0
9,1,15,1,0,3,4,1,2,0,0,...,1,0,0,0,1,0,0,0,1,0

In [7]:
student_df['goout'].describe()

count    395.000000
mean       3.108861
std        1.113278
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: goout, dtype: float64

In [8]:
student_df['freetime'].describe()

count    395.000000
mean       3.235443
std        0.998862
min        1.000000
25%        3.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: freetime, dtype: float64